title: 360 Virtual tours
author: Marc Tjon-A- tsien
email: marc@tjon-a-tsien.com
description: > # 260 tours are publidshed here "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: cramsession-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  cramsession-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
